export enum DomainErrorCode {
    INVALID_AMOUNT = 'INVALID_AMOUNT',
    CURRENCY_MISMATCH = 'CURRENCY_MISMATCH',
    INVALID_IDEMPOTENCY_KEY = 'INVALID_IDEMPOTENCY_KEY',
    INVALID_USER_ID = 'INVALID_USER_ID',
    INVALID_PAYMENT_METHOD = 'INVALID_PAYMENT_METHOD',
    INVALID_OPERATION_TRANSITION = 'INVALID_OPERATION_TRANSITION',
  }